# -- Site Configuration --
# Refer to the Hugo docs for more details:
# https://gohugo.io/getting-started/configuration/

languageCode = 'en-us'
theme = 'blowfish'

enableEmoji = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 12
