# -- Main Menu --
# Displayed in the header at the top of the page.

[[main]]
  name = "Aliens For Hire"
  pageRef = "games/aliens-for-hire"
  weight = 10

[[main]]
  name = "Portfolio"
  pageRef = "games"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

# -- Footer Menu --

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
